name: Reusable Java Build Workflow
on:
workflow_call:
inputs:
java-version:
required: true
type: string
build-command:
required: true
type: string
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v3
- name: Set up JDK
uses: actions/setup-java@v3

with:
java-version: ${{ inputs.java-version }}
distribution: 'temurin'
- name: Build Java project
run: ${{ inputs.build-command }}
