name: Reusable CI Workflow

on:
  workflow_call:
    inputs:
      repo_url:
        required: true
        type: string

    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo_url }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify POM.xml Exists
        run: |
          if [ ! -f pom.xml ]; then
            echo "Error: pom.xml not found in the directory. Ensure the correct repo is checked out."
            exit 1
          fi

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        env:
          MAVEN_OPTS: ${{ secrets.MAVEN_OPTS }}
        run: mvn package

      - name: Run WAR File
        run: |
          if ls target/*.war 1> /dev/null 2>&1; then
            java -jar target/*.war
          else
            echo "Error: No WAR file found in target directory."
            exit 1
          fi
