name: Reusable CI Workflow

on:
  workflow_call:
    inputs:
      repo_url:
        required: true
        type: string
      maven-goal:   
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    container:
      image: maven:3.8.5-openjdk-17 
    env:
      MEMORY_LIMIT: "default"
    timeout-minutes: 15
    continue-on-error: false
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        timeout-minutes: 2

      - name: Verify POM.xml Exists
        run: |
          if [ ! -f pom.xml ]; then
            echo "Error: pom.xml not found in the directory. Ensure the correct repo is checked out."
            exit 1
          fi
        working-directory: ./app  # Updated to match the working directory

      - name: Run with Maven
        id: build-step
        run: |
          mvn -B ${{ inputs.maven-goal }}
          echo "status=success" >> $GITHUB_ENV
        shell: bash
        timeout-minutes: 5

      - name: Run Tests
        run: mvn -B test
        continue-on-error: true

      - name: Cleanup Resources
        if: always()
        run: echo "Cleaning up resources after build"
