name: Reusable CI Workflow

on:
  workflow_call:
    inputs:
      repo_url:
        required: true
        type: string
      maven-goal:   
        required: true
        type: string
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.5-openjdk-17  # Fixed image
    env:
      MEMORY_LIMIT: "default"
    timeout-minutes: 15
    continue-on-error: false
    permissions:
      contents: read
    strategy:
      matrix:
        java: [11, 17]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 2

      - name: Verify POM.xml Exists
        run: |
          if [ ! -f pom.xml ]; then
            echo "Error: pom.xml not found in the directory. Ensure the correct repo is checked out."
            exit 1
          fi
        working-directory: ./

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Run with Maven
        id: build-step
        run: |
          mvn ${{ inputs.maven-goal }}
          echo "status=success" >> $GITHUB_ENV
        shell: bash
        timeout-minutes: 5

      - name: Run Tests
        run: mvn test
        continue-on-error: true

      - name: Cleanup Resources
        if: always()
        run: echo "Cleaning up resources after build"
